### PR TITLE
Remove s6 from rc.init service path

### PR DESCRIPTION
**Pull request by belka-ew**
- One README fix, `skel` is missing in the big example.
- `rc.init` change since `/run/service` seems to be the default directory used by the init maker.

### CODE REVIEW

**Comment by mumahendras3** [comment]
Hi,

Sorry for the late response, and thank you for the PR!

I'll try to look at this when I have some spare time in the weekend.

Cheers!

**Comment by mumahendras3** [comment]
> * One README fix, `skel` is missing in the big example.

Whoops, my bad. Thanks for correcting it.

> * `rc.init` change since `/run/service` seems to be the default directory used by the init maker.

Yes, the default is `/run/service`. `/run/s6/service` is just what I use on my system to organize s6-related things in one neat directory. Although, I'll probably one day reorganize things and make them closer to the defaults, just to make it easier to setup and I don't have to pass custom options when running the SlackBuild scripts :D.

Anyway, LGTM. Merging this now.

**Comment by belka-ew** [comment]
> Yes, the default is /run/service. /run/s6/service is just what I use on my system to organize s6-related things in one neat directory.

Thanks .The problem is not the directory in itself, but if someone follows the instructions in README, he ends up with the system that won't boot. If the other instructions can be adopted to `/run/s6/service` it wouldn't be a problem I suppose. Even the quick guid uses `/run/service`.

**Comment by mumahendras3** [comment]
Yeah, you're right. As I said previously, I'm planning to reorganize things on my system to stick closer to the defaults, so I might do some more README updates in the future.

**Pull request merged**
